# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Moments20191' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moments20191
    pod 'SVProgressHUD'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftLint'
    pod 'Kingfisher'
end
