# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Moments' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moments
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'Firebase/Storage'
  pod 'Kingfisher'

end
